### PR TITLE
Auto focus search

### PR DESCRIPTION
**Pull request by thedeany**
This enhancement auto-focuses the search bar on load. This was helpful for me as setting a "homepage" as the start page in the browser (at least in Safari) disables the auto-focusing of the address bar. This still allows immediate searching without having to click the address bar or use a keyboard shortcut.

### CODE REVIEW

**Comment by phntxx** [comment]
Hi,

first of all: thank you very much for this (and your two other PRs).

While all of this looks good to me, I'll hold off on merging this just now as I'd personally like to make this a user-configurable option (just like themes, for example).

I'll have a look at this once I'm free to mess around with the code of this some more myself.

Kind regards

**Comment by thedeany** [comment]
Ah, of course. That makes sense! I can certainly take a look at that as well and append it to this PR. Would you want it to take the same approach as the themes, as in saving it in `localStorage`? Or perhaps a new `settings.json` file instead (where further enhancements can be added as well)?

If we go with the `localStorage` option, we might want to consider moving everything (which is just theme and this new feature currently) to one key/value pair so all of the settings for this app are in one spot.

**Comment by thedeany** [comment]
I went ahead with adding a boolean in `search.json`. Seemed to be the easiest at this point. Either of the other methods would be a larger undertaking, so I figured I'd get this into a configurable state to get it closed and then the ideas of moving to one key/value pair or an overall `settings.json` file could be had elsewhere.

**Comment by phntxx** [comment]
Hi!

Sorry for keeping this unattended for so long. I've thought about this some more recently and figured that your key-value-pair approach in `search.json` should be fine and I just overthought this.

I've gone ahead and implemented this feature. Adding `"autoFocus": true` to `search.json` now turns on autofocus.

Kind regards
Bastian

**Pull request closed without merging**
